name: Generate Ontology Docs

on:
  push:
    branches:
      - main
      - HeritageGraph
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create docs folder
        run: mkdir -p docs

      - name: Run Widoco
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/HeritageGraph.ttl:/input/HeritageGraph.ttl \
            -v ${{ github.workspace }}/docs:/output \
            ghcr.io/dgarijo/widoco:v1.4.23 \
            -ontFile /input/HeritageGraph.ttl \
            -outFolder /output \
            -lang en \
            -rewriteAll \
            -webVowl

      - name: Rename index-en.html to index.html
        run: |
          if [ -f "${GITHUB_WORKSPACE}/docs/index-en.html" ]; then
            mv "${GITHUB_WORKSPACE}/docs/index-en.html" "${GITHUB_WORKSPACE}/docs/index.html"
          fi

      - name: Add .nojekyll
        run: touch docs/.nojekyll


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
